data_path: "classpath:data/"

---
spring:
  config:
    activate:
      on-profiles:
        default
  redis:
    host: localhost
    port: 6379

---
spring:
  config:
    activate:
      on-profiles:
        prod
  redis:
    host: redis
    port: 6379